FROM registry.suse.com/suse/ltss/sle12.5/sles12sp5:latest@sha256:4a82bd7039e8a99ca510881a51363a3e05a04124c9548e67db01029ff0eb8475

LABEL maintainer="florian.stosse@gmail.com"
LABEL lastupdate="2025-07-30"
LABEL author="Florian Stosse"
LABEL description="SLES 12 SP5 base image used for SBOM generation"