FROM registry.suse.com/bci/bci-minimal:15.7@sha256:68c9ed6b61ddd682ce93002454a787aad6ffdc51afc2c17b71cad9ef2a021429

LABEL maintainer="florian.stosse@gmail.com"
LABEL lastupdate="2025-07-30"
LABEL author="Florian Stosse"
LABEL description="SLES 15 SP7 Minimal base image used for SBOM generation"

RUN pwd